#!/usr/bin/env python

import sys
sys.path.insert(0,"/home/rudd-o/Projects/Mine/musictoolbox/lib")
import musictoolbox
import logging
logging.basicConfig(level=logging.DEBUG)

args = sys.argv[1:]
assert len(args) > 1
musictoolbox.parallel_transcode(args[0],args[1:])